# Generated by Django 2.2.5 on 2019-10-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcat',
            name='img',
            field=models.ImageField(blank=True, upload_to='PCat_img/'),
        ),
        migrations.AlterField(
            model_name='psubcat',
            name='img',
            field=models.ImageField(blank=True, upload_to='PSubCat_img/'),
        ),
    ]
