# Generated by Django 2.2.5 on 2019-10-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191014_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcat',
            name='img',
            field=models.ImageField(blank=True, default='PCat_img/test.jpg', upload_to='PCat_img/'),
        ),
    ]
