# Generated by Django 2.2.5 on 2019-10-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191014_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('products_watchlist', models.ManyToManyField(to='website.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Commments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Product')),
                ('user', models.ForeignKey(default='none', on_delete=django.db.models.deletion.SET_DEFAULT, to='website.UserProfile')),
            ],
        ),
    ]
